=== todorm85/TelerikAcademy/Courses/Software Technologies/Databases/Homework/01. XML Basics/students-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:students"
           xmlns="urn:students"
           elementFormDefault="qualified">
    <!-- For more info on this method of schema definition see: http://www.w3schools.com/schema/schema_example.asp -->

    <!-- simple elements -->

    <xs:element name="name" type="xs:string"/>
    <xs:element name="gender" type="xs:string"/>
    <xs:element name="birth_date" type="xs:date"/>
    <xs:element name="phone" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="course" type="xs:string"/>
    <xs:element name="specialty" type="xs:string"/>
    <xs:element name="faculty_number" type="xs:string"/>
    <xs:element name="tutor" type="xs:string"/>
    <xs:element name="score" type="xs:decimal"/>

    <!-- complex elements -->

    <xs:element name="exams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exam" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="name"/>
                            <xs:element ref="tutor"/>
                            <xs:element ref="score"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="name"/>
                            <xs:element ref="gender"/>
                            <xs:element ref="birth_date"/>
                            <xs:element ref="phone"/>
                            <xs:element ref="email"/>
                            <xs:element ref="course"/>
                            <xs:element ref="specialty"/>
                            <xs:element ref="faculty_number"/>
                            <xs:element ref="exams"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== todorm85/TelerikAcademy/Courses/Software Technologies/Databases/Homework/01. XML Basics/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students-style.xsl"?>

<students xmlns="urn:students"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:students students-schema.xsd">
    <student>
        <name>Alfred</name>
        <gender>male</gender>
        <birth_date>2015-01-01</birth_date>
        <phone>+359886111111</phone>
        <email>alfred@alfred.com</email>
        <course>java</course>
        <specialty>QA</specialty>
        <faculty_number>111</faculty_number>
        <exams>
            <exam>
                <name>C#1</name>
                <tutor>Gosho</tutor>
                <score>6</score>
            </exam>
            <exam>
                <name>C#2</name>
                <tutor>Gosho</tutor>
                <score>4</score>
            </exam>
            <exam>
                <name>JS</name>
                <score>3</score>
                <tutor>Dragancho</tutor>
            </exam>
        </exams>
    </student>
    <student>
        <name>Dana</name>
        <gender>female</gender>
        <birth_date>2015-01-01</birth_date>
        <phone>+359886222111</phone>
        <email>dana@alfred.com</email>
        <course>Java Script</course>
        <specialty>Developer</specialty>
        <faculty_number>1111</faculty_number>
        <exams>
            <exam>
                <name>C#1</name>
                <tutor>Gosho</tutor>
                <score>5</score>
            </exam>
        </exams>
    </student>
    <student>
        <name>Haralampi</name>
        <gender>male</gender>
        <birth_date>2013-01-01</birth_date>
        <phone>+359886131541</phone>
        <email>dsfd@haralampi.com</email>
        <course>html</course>
        <specialty>front-end</specialty>
        <faculty_number>114</faculty_number>
        <exams>
            <exam>
                <name>C#1</name>
                <tutor>Gosho</tutor>
                <score>3</score>
            </exam>
            <exam>
                <name>C#2</name>
                <tutor>Gosho</tutor>
                <score>2</score>
            </exam>
            <exam>
                <name>JS</name>
                <score>6</score>
                <tutor>Dragancho</tutor>
            </exam>
        </exams>
    </student>
</students>
